// Code generated by go-wireset-gen. DO NOT EDIT.

package di

import (
	config "github.com/graphzc/go-task-clean-example/internal/config"
	handlers "github.com/graphzc/go-task-clean-example/internal/handlers"
	auth "github.com/graphzc/go-task-clean-example/internal/handlers/auth"
	common "github.com/graphzc/go-task-clean-example/internal/handlers/common"
	context "github.com/graphzc/go-task-clean-example/internal/infrastructure/context"
	database "github.com/graphzc/go-task-clean-example/internal/infrastructure/database"
	user "github.com/graphzc/go-task-clean-example/internal/repositories/user"
	user2 "github.com/graphzc/go-task-clean-example/internal/services/user"

	"github.com/google/wire"
)

var ConfigSet = wire.NewSet(
	config.NewConfig,
)

var HandlerSet = wire.NewSet(
	handlers.NewHandlers,
	auth.New,
	common.New,
)

var InfrastructureSet = wire.NewSet(
	context.NewContext,
	database.NewSQLXClient,
)

var RepositorySet = wire.NewSet(
	user.NewRepository,
)

var ServiceSet = wire.NewSet(
	user2.NewService,
)
