// Code generated by go-wireset-gen. DO NOT EDIT.

package di

import (
	config "github.com/graphzc/go-clean-template/internal/config"
	handlers "github.com/graphzc/go-clean-template/internal/handlers"
	common "github.com/graphzc/go-clean-template/internal/handlers/common"
	foo "github.com/graphzc/go-clean-template/internal/handlers/foo"
	context "github.com/graphzc/go-clean-template/internal/infrastructure/context"
	database "github.com/graphzc/go-clean-template/internal/infrastructure/database"
	foo2 "github.com/graphzc/go-clean-template/internal/repositories/foo"
	foo3 "github.com/graphzc/go-clean-template/internal/services/foo"

	"github.com/google/wire"
)

var ConfigSet = wire.NewSet(
	config.NewConfig,
)

var HandlerSet = wire.NewSet(
	handlers.NewHandlers,
	common.New,
	foo.New,
)

var InfrastructureSet = wire.NewSet(
	context.NewContext,
	database.NewSQLXClient,
)

var RepositorySet = wire.NewSet(
	foo2.NewRepository,
)

var ServiceSet = wire.NewSet(
	foo3.NewService,
)
