// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/graphzc/go-clean-template/cmd/api/server"
	"github.com/graphzc/go-clean-template/internal/config"
	"github.com/graphzc/go-clean-template/internal/handlers"
	"github.com/graphzc/go-clean-template/internal/handlers/common"
	foo3 "github.com/graphzc/go-clean-template/internal/handlers/foo"
	"github.com/graphzc/go-clean-template/internal/infrastructure/context"
	"github.com/graphzc/go-clean-template/internal/infrastructure/database"
	"github.com/graphzc/go-clean-template/internal/repositories/foo"
	foo2 "github.com/graphzc/go-clean-template/internal/services/foo"
)

// Injectors from wire.go:

func InitializeAPI() *server.EchoServer {
	configConfig := config.NewConfig()
	handler := common.New()
	contextContext := context.NewContext()
	db := database.NewSQLXClient(contextContext, configConfig)
	repository := foo.NewRepository(db)
	service := foo2.NewService(configConfig, repository)
	fooHandler := foo3.New(service)
	handlersHandlers := handlers.NewHandlers(handler, fooHandler)
	echoServer := server.NewEchoServer(configConfig, handlersHandlers)
	return echoServer
}
