// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/graphzc/go-task-clean-example/cmd/api/server"
	"github.com/graphzc/go-task-clean-example/internal/config"
	"github.com/graphzc/go-task-clean-example/internal/handlers"
	"github.com/graphzc/go-task-clean-example/internal/handlers/auth"
	"github.com/graphzc/go-task-clean-example/internal/handlers/common"
	"github.com/graphzc/go-task-clean-example/internal/infrastructure/context"
	"github.com/graphzc/go-task-clean-example/internal/infrastructure/database"
	"github.com/graphzc/go-task-clean-example/internal/repositories/user"
	user2 "github.com/graphzc/go-task-clean-example/internal/services/user"
)

// Injectors from wire.go:

func InitializeAPI() *server.EchoServer {
	configConfig := config.NewConfig()
	handler := common.New()
	contextContext := context.NewContext()
	db := database.NewSQLXClient(contextContext, configConfig)
	repository := user.NewRepository(db)
	service := user2.NewService(configConfig, repository)
	authHandler := auth.New(service)
	handlersHandlers := handlers.NewHandlers(handler, authHandler)
	echoServer := server.NewEchoServer(configConfig, handlersHandlers)
	return echoServer
}
